#################################################
# RANDOM IDS
#################################################

resource "random_id" "logs" {
  byte_length = 4
}

resource "random_id" "ui" {
  byte_length = 4
}

#################################################
# CLOUDTRAIL LOGS BUCKET (PRIVATE)
#################################################

resource "aws_s3_bucket" "logs" {
  bucket = "soc-copilot-logs-${random_id.logs.hex}"
}

# Block all public access to the audit-log bucket.
resource "aws_s3_bucket_public_access_block" "logs" {
  bucket                  = aws_s3_bucket.logs.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "logs" {
  bucket = aws_s3_bucket.logs.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Preserve prior versions so tampered/deleted audit logs can be recovered.
resource "aws_s3_bucket_versioning" "logs" {
  bucket = aws_s3_bucket.logs.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_policy" "cloudtrail_policy" {
  bucket = aws_s3_bucket.logs.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "AWSCloudTrailAclCheck"
        Effect = "Allow"
        Principal = {
          Service = "cloudtrail.amazonaws.com"
        }
        Action   = "s3:GetBucketAcl"
        Resource = aws_s3_bucket.logs.arn
        Condition = {
          StringEquals = {
            "aws:SourceArn" = "arn:aws:cloudtrail:${data.aws_region.current.region}:${data.aws_caller_identity.current.account_id}:trail/soc-copilot-trail"
          }
        }
      },
      {
        Sid    = "AWSCloudTrailWrite"
        Effect = "Allow"
        Principal = {
          Service = "cloudtrail.amazonaws.com"
        }
        Action   = "s3:PutObject"
        Resource = "${aws_s3_bucket.logs.arn}/*"
        Condition = {
          StringEquals = {
            "s3:x-amz-acl"  = "bucket-owner-full-control"
            "aws:SourceArn" = "arn:aws:cloudtrail:${data.aws_region.current.region}:${data.aws_caller_identity.current.account_id}:trail/soc-copilot-trail"
          }
        }
      }
    ]
  })
}

#################################################
# CHAT UI BUCKET (PRIVATE)
#################################################

resource "aws_s3_bucket" "chat_ui" {
  bucket = "soc-copilot-ui-${random_id.ui.hex}"
}

resource "aws_s3_bucket_public_access_block" "chat_ui" {
  bucket                  = aws_s3_bucket.chat_ui.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "chat_ui" {
  bucket = aws_s3_bucket.chat_ui.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_object" "chat_index" {
  bucket       = aws_s3_bucket.chat_ui.id
  key          = "index.html"
  source       = "${path.module}/chat_ui/index.html"
  content_type = "text/html"
  etag         = filemd5("${path.module}/chat_ui/index.html")
}

resource "aws_s3_object" "chat_script" {
  bucket       = aws_s3_bucket.chat_ui.id
  key          = "script.js"
  source       = "${path.module}/chat_ui/script.js"
  content_type = "application/javascript"
  etag         = filemd5("${path.module}/chat_ui/script.js")
}

# Runtime config injected at deploy time so the SPA knows its Cognito
# settings and API endpoint without hardcoding them in source.
resource "aws_s3_object" "chat_config" {
  bucket       = aws_s3_bucket.chat_ui.id
  key          = "config.js"
  content_type = "application/javascript"

  content = <<-EOT
    // Generated by Terraform — do not edit by hand.
    window.SOC_CONFIG = {
      apiEndpoint:   "https://${aws_cloudfront_distribution.soc_api.domain_name}/analyze",
      cognitoDomain: "https://${aws_cognito_user_pool_domain.soc.domain}.auth.${data.aws_region.current.region}.amazoncognito.com",
      clientId:      "${aws_cognito_user_pool_client.soc_web.id}",
      redirectUri:   "https://${aws_cloudfront_distribution.chat_ui.domain_name}/",
      scopes:        "openid email profile"
    };
  EOT

  # Force re-upload whenever any value changes.
  etag = md5(join(",", [
    aws_cloudfront_distribution.soc_api.domain_name,
    aws_cognito_user_pool_domain.soc.domain,
    aws_cognito_user_pool_client.soc_web.id,
    aws_cloudfront_distribution.chat_ui.domain_name,
  ]))
}

#################################################
# CLOUDFRONT SECURE ACCESS
#################################################

resource "aws_cloudfront_origin_access_control" "chat_ui" {
  name                              = "soc-copilot-oac"
  description                       = "Secure access to private S3"
  origin_access_control_origin_type = "s3"
  signing_behavior                  = "always"
  signing_protocol                  = "sigv4"
}

resource "aws_s3_bucket_policy" "chat_ui_private" {
  bucket = aws_s3_bucket.chat_ui.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = {
        Service = "cloudfront.amazonaws.com"
      }
      Action   = "s3:GetObject"
      Resource = "${aws_s3_bucket.chat_ui.arn}/*"
      # Restrict to this specific distribution (prevents confused-deputy).
      Condition = {
        StringEquals = {
          "AWS:SourceArn" = aws_cloudfront_distribution.chat_ui.arn
        }
      }
    }]
  })
}

resource "aws_cloudfront_distribution" "chat_ui" {
  enabled             = true
  default_root_object = "index.html"

  origin {
    domain_name              = aws_s3_bucket.chat_ui.bucket_regional_domain_name
    origin_id                = "chat-ui"
    origin_access_control_id = aws_cloudfront_origin_access_control.chat_ui.id
  }

  default_cache_behavior {
    target_origin_id       = "chat-ui"
    viewer_protocol_policy = "redirect-to-https"

    allowed_methods = ["GET", "HEAD"]
    cached_methods  = ["GET", "HEAD"]

    forwarded_values {
      query_string = false
      cookies {
        forward = "none"
      }
    }
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }
}

#################################################
# OUTPUT
#################################################

output "chat_ui_url" {
  value = "https://${aws_cloudfront_distribution.chat_ui.domain_name}"
}
